var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/attendance/route.js")
R.c("server/chunks/_0dgaobn._.js")
R.c("server/chunks/[root-of-the-server]__0ga-2r9._.js")
R.c("server/chunks/[root-of-the-server]__0xi-zcw._.js")
R.c("server/chunks/_0qubx0o._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/lib_notifications_whatsapp_ts_0hzky4g._.js")
R.c("server/chunks/_next-internal_server_app_api_attendance_route_actions_1030dcd.js")
R.m(551309)
module.exports=R.m(551309).exports
