var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/finance/invoices/route.js")
R.c("server/chunks/[root-of-the-server]__0q9gxuv._.js")
R.c("server/chunks/lib_notifications_whatsapp_ts_0hzky4g._.js")
R.c("server/chunks/_0hs29on._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_0qubx0o._.js")
R.c("server/chunks/[root-of-the-server]__0ga-2r9._.js")
R.c("server/chunks/_next-internal_server_app_api_finance_invoices_route_actions_0-0u8~7.js")
R.m(976748)
module.exports=R.m(976748).exports
