var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/clinical/operations/pharmacy-dispense/route.js")
R.c("server/chunks/[root-of-the-server]__0qme7wk._.js")
R.c("server/chunks/lib_clinical_0jd2wkg._.js")
R.c("server/chunks/_04fd7fw._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/[root-of-the-server]__0ga-2r9._.js")
R.c("server/chunks/_0qubx0o._.js")
R.c("server/chunks/0zjb_server_app_api_clinical_operations_pharmacy-dispense_route_actions_0.ko55l.js")
R.m(644157)
module.exports=R.m(644157).exports
