var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/clinical-services/discharges/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-cehvt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_05uz5z0.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qx7kg_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k~tbvx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_clinical-services_discharges_[id]_page_actions_02y1v1~.js")
R.m(398919)
module.exports=R.m(398919).exports
