var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/settings/academic-years/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__004pf3k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_117.mu..js")
R.c("server/chunks/ssr/[root-of-the-server]__0qx7kg_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k~tbvx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_settings_academic-years_page_actions_077l1n_.js")
R.m(334030)
module.exports=R.m(334030).exports
