var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/clinical/billing/invoices/route.js")
R.c("server/chunks/[root-of-the-server]__0qme7wk._.js")
R.c("server/chunks/lib_clinical_0jd2wkg._.js")
R.c("server/chunks/_0..hyxr._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/[root-of-the-server]__0ga-2r9._.js")
R.c("server/chunks/_0qubx0o._.js")
R.c("server/chunks/_next-internal_server_app_api_clinical_billing_invoices_route_actions_043.rcr.js")
R.m(418134)
module.exports=R.m(418134).exports
