var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/clinical-services/ward-management/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0--~ux0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_08yxqsc.js")
R.c("server/chunks/ssr/node_modules_next_dist_11dij6w._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qx7kg_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k~tbvx._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/0zjb_server_app_clinical-services_ward-management_[id]_page_actions_06ykyrn.js")
R.m(995013)
module.exports=R.m(995013).exports
