var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/clinical/platform/hospitals/route.js")
R.c("server/chunks/[root-of-the-server]__06wh545._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0bjz0ul.js")
R.c("server/chunks/[root-of-the-server]__0ga-2r9._.js")
R.c("server/chunks/[root-of-the-server]__0v8bdq7._.js")
R.c("server/chunks/_0qubx0o._.js")
R.c("server/chunks/_0ipb.wv._.js")
R.c("server/chunks/_next-internal_server_app_api_clinical_platform_hospitals_route_actions_0n-a635.js")
R.m(545149)
module.exports=R.m(545149).exports
